import type { Scenario } from './types'

export const scenario: Scenario = {
  id: 'click-fetch-render',
  title: 'Click → Fetch → DOM Update',
  codeLines: [
    { text: "button.addEventListener('click', () => {", id: 'addEventListener' },
    { text: '  console.log("Click handler start")', id: 'log-click' },
    { text: '', id: 'blank1' },
    { text: '  fetch("/api/data")', id: 'fetch-call' },
    { text: '    .then(res => res.json())', id: 'then-json' },
    { text: '    .then(data => {', id: 'then-data' },
    { text: '      console.log("Data received")', id: 'log-data' },
    { text: '      document.getElementById("result")', id: 'dom-get' },
    { text: '        .textContent = data.message', id: 'dom-set' },
    { text: '    })', id: 'then-close' },
    { text: '', id: 'blank2' },
    { text: '  queueMicrotask(() => {', id: 'queue-micro' },
    { text: '    console.log("Microtask 1")', id: 'log-micro1' },
    { text: '  })', id: 'micro-close' },
    { text: '', id: 'blank3' },
    { text: '  requestAnimationFrame(() => {', id: 'raf-call' },
    { text: '    element.style.opacity = "1"', id: 'raf-opacity' },
    { text: '    element.classList.add("visible")', id: 'raf-class' },
    { text: '  })', id: 'raf-close' },
    { text: '', id: 'blank4' },
    { text: '  setTimeout(() => {', id: 'set-timeout' },
    { text: '    console.log("Timeout fired")', id: 'log-timeout' },
    { text: '    Promise.resolve().then(() => {', id: 'promise-in-timeout' },
    { text: '      console.log("Micro in timeout")', id: 'log-micro-timeout' },
    { text: '    })', id: 'promise-close' },
    { text: '  }, 0)', id: 'timeout-close' },
    { text: '', id: 'blank5' },
    { text: '  console.log("Click handler end")', id: 'log-end' },
    { text: '})', id: 'handler-close' },
  ],
  steps: [
    {
      title: 'User clicks button',
      desc: 'Browser detects click event and queues the callback as a macrotask',
      activePhase: null,
      highlightLines: ['addEventListener'],
      callStack: [],
      queues: { task: ['click callback'] },
      webAPIs: [],
      badge: { text: '1', color: '#3b82f6' },
    },
    {
      title: 'Macrotask: Execute click handler',
      desc: 'Event loop picks up the click callback from the task queue and pushes it onto the call stack',
      activePhase: 'macrotask',
      highlightLines: ['addEventListener', 'log-click'],
      executedLines: ['addEventListener', 'log-click'],
      callStack: ['click callback', 'console.log("Click handler start")'],
      queues: {},
      webAPIs: [],
      badge: { text: '2', color: '#3b82f6' },
    },
    {
      title: 'Register fetch()',
      desc: 'fetch() is called — the browser hands the network request to the Web API layer (runs in parallel)',
      activePhase: 'macrotask',
      highlightLines: ['fetch-call', 'then-json', 'then-data', 'then-close'],
      executedLines: ['fetch-call'],
      callStack: ['click callback', 'fetch("/api/data")'],
      queues: {},
      webAPIs: ['fetch → /api/data'],
      badge: { text: '3', color: '#3b82f6' },
    },
    {
      title: 'Register queueMicrotask()',
      desc: 'queueMicrotask() immediately places the callback into the microtask queue',
      activePhase: 'macrotask',
      highlightLines: ['queue-micro', 'log-micro1', 'micro-close'],
      executedLines: ['queue-micro'],
      callStack: ['click callback', 'queueMicrotask()'],
      queues: { microtask: ['Microtask 1'] },
      webAPIs: ['fetch → /api/data'],
      badge: { text: '4', color: '#3b82f6' },
    },
    {
      title: 'Register requestAnimationFrame()',
      desc: 'rAF callback is registered — it will run before the next repaint, not immediately',
      activePhase: 'macrotask',
      highlightLines: ['raf-call', 'raf-opacity', 'raf-class', 'raf-close'],
      executedLines: ['raf-call'],
      callStack: ['click callback', 'requestAnimationFrame()'],
      queues: { microtask: ['Microtask 1'], raf: ['opacity + class'] },
      webAPIs: ['fetch → /api/data'],
      badge: { text: '5', color: '#3b82f6' },
    },
    {
      title: 'Register setTimeout(, 0)',
      desc: 'setTimeout(fn, 0) hands the timer to the Web API layer. Even with 0ms delay, the callback goes to the task queue later',
      activePhase: 'macrotask',
      highlightLines: ['set-timeout', 'log-timeout', 'promise-in-timeout', 'log-micro-timeout', 'promise-close', 'timeout-close'],
      executedLines: ['set-timeout'],
      callStack: ['click callback', 'setTimeout()'],
      queues: { microtask: ['Microtask 1'], raf: ['opacity + class'] },
      webAPIs: ['fetch → /api/data', 'Timer (0ms)'],
      badge: { text: '6', color: '#3b82f6' },
    },
    {
      title: 'Finish click handler',
      desc: 'console.log("Click handler end") executes. The macrotask (click callback) is now complete — call stack empties',
      activePhase: 'macrotask',
      highlightLines: ['log-end', 'handler-close'],
      executedLines: ['log-end', 'handler-close'],
      callStack: ['click callback', 'console.log("Click handler end")'],
      queues: { microtask: ['Microtask 1'], raf: ['opacity + class'] },
      webAPIs: ['fetch → /api/data', 'Timer (0ms)'],
      badge: { text: '7', color: '#3b82f6' },
    },
    {
      title: 'Microtask checkpoint',
      desc: 'After the macrotask completes, the event loop MUST drain all microtasks before doing anything else',
      activePhase: 'microtask',
      highlightLines: ['queue-micro', 'log-micro1', 'micro-close'],
      executedLines: ['log-micro1'],
      callStack: ['Microtask 1', 'console.log("Microtask 1")'],
      queues: {},
      webAPIs: ['fetch → /api/data', 'Timer (0ms)'],
      badge: { text: '8', color: '#a855f7' },
    },
    {
      title: 'Microtask queue drained',
      desc: 'All microtasks are done. The event loop can now proceed to rendering',
      activePhase: 'microtask',
      highlightLines: [],
      callStack: [],
      queues: {},
      webAPIs: ['fetch → /api/data', 'Timer (0ms)'],
      badge: { text: '9', color: '#a855f7' },
    },
    {
      title: 'requestAnimationFrame callbacks',
      desc: 'Before painting, the browser runs all rAF callbacks registered during this frame',
      activePhase: 'raf',
      highlightLines: ['raf-call', 'raf-opacity', 'raf-class', 'raf-close'],
      executedLines: ['raf-opacity', 'raf-class'],
      callStack: ['rAF callback', 'element.style.opacity = "1"'],
      queues: {},
      webAPIs: ['fetch → /api/data', 'Timer (0ms)'],
      badge: { text: '10', color: '#22c55e' },
    },
    {
      title: 'Render: Style calculation',
      desc: 'Browser recalculates computed styles for all affected elements (cascading, inheritance)',
      activePhase: 'render',
      highlightLines: [],
      callStack: ['[Style]'],
      queues: {},
      webAPIs: ['fetch → /api/data', 'Timer (0ms)'],
      badge: { text: '11', color: '#f43f5e' },
    },
    {
      title: 'Render: Layout',
      desc: 'Browser computes geometry — positions and sizes of elements in the render tree',
      activePhase: 'render',
      highlightLines: [],
      callStack: ['[Layout]'],
      queues: {},
      webAPIs: ['fetch → /api/data', 'Timer (0ms)'],
      badge: { text: '12', color: '#f43f5e' },
    },
    {
      title: 'Render: Paint + Composite',
      desc: 'Pixels are drawn to layers and composited to the screen. The frame is now visible to the user',
      activePhase: 'render',
      highlightLines: [],
      callStack: ['[Paint + Composite]'],
      queues: {},
      webAPIs: ['fetch → /api/data', 'Timer (0ms)'],
      badge: { text: '13', color: '#f43f5e' },
    },
    {
      title: 'Timer fires → task queue',
      desc: 'The 0ms timer has elapsed in the Web API layer. Its callback moves to the task queue',
      activePhase: 'idle',
      highlightLines: ['set-timeout'],
      callStack: [],
      queues: { task: ['setTimeout callback'] },
      webAPIs: ['fetch → /api/data'],
      badge: { text: '14', color: '#6b7280' },
    },
    {
      title: 'Macrotask: setTimeout callback',
      desc: 'Event loop picks the setTimeout callback from the task queue',
      activePhase: 'macrotask',
      highlightLines: ['log-timeout', 'promise-in-timeout', 'log-micro-timeout', 'promise-close'],
      executedLines: ['log-timeout'],
      callStack: ['setTimeout callback', 'console.log("Timeout fired")'],
      queues: {},
      webAPIs: ['fetch → /api/data'],
      badge: { text: '15', color: '#3b82f6' },
    },
    {
      title: 'Promise.resolve() in timeout',
      desc: 'Promise.resolve().then() schedules a microtask from inside the setTimeout callback',
      activePhase: 'macrotask',
      highlightLines: ['promise-in-timeout', 'log-micro-timeout', 'promise-close'],
      executedLines: ['promise-in-timeout'],
      callStack: ['setTimeout callback', 'Promise.resolve().then()'],
      queues: { microtask: ['Micro in timeout'] },
      webAPIs: ['fetch → /api/data'],
      badge: { text: '16', color: '#3b82f6' },
    },
    {
      title: 'Drain microtasks again',
      desc: 'After setTimeout callback finishes, the microtask checkpoint fires again and drains the queue',
      activePhase: 'microtask',
      highlightLines: ['log-micro-timeout'],
      executedLines: ['log-micro-timeout'],
      callStack: ['Promise .then()', 'console.log("Micro in timeout")'],
      queues: {},
      webAPIs: ['fetch → /api/data'],
      badge: { text: '17', color: '#a855f7' },
    },
    {
      title: 'Idle: waiting for I/O',
      desc: 'No tasks or microtasks pending. The event loop is idle, waiting for the network response',
      activePhase: 'idle',
      highlightLines: [],
      callStack: [],
      queues: {},
      webAPIs: ['fetch → /api/data'],
      badge: { text: '18', color: '#6b7280' },
    },
    {
      title: 'Fetch response arrives',
      desc: 'Network response completes in the Web API layer. The .then() callbacks are scheduled as microtasks',
      activePhase: null,
      highlightLines: ['then-json'],
      callStack: [],
      queues: { microtask: ['res.json()'] },
      webAPIs: [],
      badge: { text: '19', color: '#3b82f6' },
    },
    {
      title: 'Microtask: res.json()',
      desc: 'First .then() parses the JSON response. The next .then() is chained as another microtask',
      activePhase: 'microtask',
      highlightLines: ['then-json'],
      executedLines: ['then-json'],
      callStack: ['Promise .then()', 'res.json()'],
      queues: { microtask: ['data => { ... }'] },
      webAPIs: [],
      badge: { text: '20', color: '#a855f7' },
    },
    {
      title: 'Microtask: Update DOM',
      desc: 'Second .then() receives parsed data and updates the DOM. Microtask queue is now empty',
      activePhase: 'microtask',
      highlightLines: ['then-data', 'log-data', 'dom-get', 'dom-set', 'then-close'],
      executedLines: ['then-data', 'log-data', 'dom-get', 'dom-set'],
      callStack: ['Promise .then()', 'textContent = data.message'],
      queues: {},
      webAPIs: [],
      badge: { text: '21', color: '#a855f7' },
    },
    {
      title: 'Render: repaint DOM change',
      desc: 'The DOM mutation triggers a new render cycle: Style → Layout → Paint to show updated text',
      activePhase: 'render',
      highlightLines: [],
      callStack: ['[Style → Layout → Paint]'],
      queues: {},
      webAPIs: [],
      badge: { text: '22', color: '#f43f5e' },
    },
    {
      title: 'Complete',
      desc: 'All tasks processed. The event loop returns to idle, ready for the next user interaction',
      activePhase: 'idle',
      highlightLines: [],
      callStack: [],
      queues: {},
      webAPIs: [],
      badge: { text: '23', color: '#6b7280' },
    },
  ],
}
