import type { Scenario } from './types'

export const scenario: Scenario = {
  id: 'http-request-lifecycle',
  title: 'Event Loop Architecture',
  codeLines: [
    { text: "const app = require('fastify')();", id: 'setup' },
    { text: '', id: 'blank1' },
    { text: "app.get('/api/user/:id', async (req, reply) => {", id: 'handler-start' },
    { text: "  console.log('Handler called');", id: 'handler-log' },
    { text: '', id: 'blank2' },
    { text: '  // Schedule microtasks', id: 'comment-micro' },
    { text: '  process.nextTick(() => {', id: 'nexttick-schedule' },
    { text: "    console.log('nextTick: validate session');", id: 'nexttick-body' },
    { text: '  });', id: 'nexttick-end' },
    { text: '', id: 'blank3' },
    { text: '  const userPromise = db.query(', id: 'db-query' },
    { text: "    'SELECT * FROM users WHERE id = $1',", id: 'db-sql' },
    { text: '    [req.params.id]', id: 'db-param' },
    { text: '  );', id: 'db-end' },
    { text: '', id: 'blank4' },
    { text: '  // Schedule timer for timeout', id: 'comment-timer' },
    { text: '  const timeout = setTimeout(() => {', id: 'timer-schedule' },
    { text: "    console.log('Timeout: request too slow');", id: 'timer-body' },
    { text: '  }, 5000);', id: 'timer-end' },
    { text: '', id: 'blank5' },
    { text: '  // Await DB result (I/O)', id: 'comment-io' },
    { text: '  const user = await userPromise;', id: 'await-db' },
    { text: '', id: 'blank6' },
    { text: '  // After I/O: schedule cleanup', id: 'comment-after' },
    { text: '  setImmediate(() => {', id: 'immediate-schedule' },
    { text: "    console.log('setImmediate: cache update');", id: 'immediate-body' },
    { text: '  });', id: 'immediate-end' },
    { text: '', id: 'blank7' },
    { text: '  clearTimeout(timeout);', id: 'clear-timeout' },
    { text: '  reply.send({ user });', id: 'send-response' },
    { text: '});', id: 'handler-close' },
    { text: '', id: 'blank8' },
    { text: 'app.listen({ port: 3000 });', id: 'listen' },
  ],
  steps: [
    {
      title: 'HTTP Request den Node.js',
      desc: 'Client gui GET /api/user/42. Request duoc OS kernel nhan va bao cho libuv thong qua epoll/kqueue. Event loop dang o Poll phase, nhan duoc event va tao callback.',
      activePhase: null,
      highlightLines: ['listen'],
      callStack: [],
      queues: { poll: ['http.onRequest(GET /api/user/42)'] },
      threadPool: [],
      badge: { text: '1', color: '#22c55e' },
    },
    {
      title: 'Poll Phase: Xu ly I/O callback',
      desc: 'Event loop dang o Poll phase. Lay callback tu poll queue va day vao Call Stack. Luc nay route handler bat dau chay DONG BO.',
      activePhase: 'poll',
      highlightLines: ['handler-start', 'handler-log'],
      callStack: ['http.onRequest()', 'routeHandler(req, reply)'],
      queues: { poll: [] },
      threadPool: [],
      badge: { text: '2', color: '#3b82f6' },
    },
    {
      title: 'Sync: Schedule nextTick',
      desc: 'Code dong bo goi process.nextTick(). Callback KHONG chay ngay, ma duoc push vao nextTick queue. Day la microtask co priority cao nhat.',
      activePhase: 'poll',
      highlightLines: ['nexttick-schedule', 'nexttick-body', 'nexttick-end'],
      callStack: ['routeHandler()', 'process.nextTick()'],
      queues: { nexttick: ['validate session'] },
      threadPool: [],
      badge: { text: '3', color: '#ec4899' },
    },
    {
      title: 'Sync: Schedule DB query (I/O)',
      desc: 'db.query() gui SQL query xuong. Viec nay duoc delegate cho Thread Pool cua libuv (vi disk/network I/O). Main thread KHONG bi block, tiep tuc chay code dong bo.',
      activePhase: 'poll',
      highlightLines: ['db-query', 'db-sql', 'db-param', 'db-end'],
      callStack: ['routeHandler()', 'db.query()'],
      queues: { nexttick: ['validate session'] },
      threadPool: ['SQL: SELECT * FROM users WHERE id=42'],
      badge: { text: '4', color: '#f97316' },
    },
    {
      title: 'Sync: Schedule setTimeout',
      desc: 'setTimeout(fn, 5000) dang ky 1 timer. Callback chua chay - no se duoc them vao Timer queue khi het 5s. Timer duoc quan ly boi libuv dung min-heap.',
      activePhase: 'poll',
      highlightLines: ['timer-schedule', 'timer-body', 'timer-end'],
      callStack: ['routeHandler()', 'setTimeout()'],
      queues: { nexttick: ['validate session'], timer: ['timeout (5000ms)'] },
      threadPool: ['SQL: SELECT * FROM users ...'],
      badge: { text: '5', color: '#f59e0b' },
    },
    {
      title: 'Sync: await userPromise',
      desc: 'Gap await -> routeHandler() bi PAUSE (thoat khoi call stack). Control tra ve event loop. Nhung truoc do, tat ca MICROTASKS phai duoc drain truoc.',
      activePhase: 'poll',
      highlightLines: ['await-db'],
      callStack: [],
      queues: { nexttick: ['validate session'], timer: ['timeout (5000ms)'] },
      threadPool: ['SQL: SELECT * FROM users ...'],
      badge: { text: '6', color: '#3b82f6' },
    },
    {
      title: 'Microtasks: Drain nextTick queue',
      desc: 'Truoc khi chuyen phase, event loop DRAIN het nextTick queue. nextTick co priority cao hon Promise. Callback "validate session" duoc day len call stack va thuc thi.',
      activePhase: null,
      activeMicrotask: 'nexttick',
      highlightLines: ['nexttick-body'],
      executedLines: ['nexttick-schedule', 'nexttick-end'],
      callStack: ['nextTickCallback()', 'console.log("validate session")'],
      queues: { nexttick: [], timer: ['timeout (5000ms)'] },
      threadPool: ['SQL: SELECT * FROM users ...'],
      badge: { text: '7', color: '#ec4899' },
    },
    {
      title: 'Microtasks: Check Promise queue',
      desc: 'Sau khi nextTick drain het, event loop check Promise queue. Hien tai Promise queue rong (DB query chua xong). Event loop tiep tuc vong lap.',
      activePhase: null,
      activeMicrotask: 'promise',
      highlightLines: [],
      callStack: [],
      queues: { timer: ['timeout (5000ms)'] },
      threadPool: ['SQL: SELECT * FROM users ...'],
      badge: { text: '8', color: '#06b6d4' },
    },
    {
      title: 'Check Phase: setImmediate queue',
      desc: 'Event loop chuyen sang Check phase. Hien tai khong co setImmediate nao duoc schedule, nen phase nay bi skip.',
      activePhase: 'check',
      highlightLines: [],
      callStack: [],
      queues: { timer: ['timeout (5000ms)'] },
      threadPool: ['SQL: SELECT * FROM users ...'],
      badge: { text: '9', color: '#10b981' },
    },
    {
      title: 'Close Callbacks Phase',
      desc: 'Phase cuoi cung. Khong co socket close event nao. Skip va bat dau VONG LAP MOI cua event loop.',
      activePhase: 'close',
      highlightLines: [],
      callStack: [],
      queues: { timer: ['timeout (5000ms)'] },
      threadPool: ['SQL: SELECT * FROM users ...'],
      badge: { text: '10', color: '#8b5cf6' },
    },
    {
      title: 'Timers Phase (vong lap moi)',
      desc: 'Vong lap moi bat dau tu Timers phase. setTimeout(5000ms) chua het han (moi chi vao ms dau tien). Khong co timer nao can xu ly, event loop chuyen sang phase tiep theo.',
      activePhase: 'timers',
      highlightLines: [],
      callStack: [],
      queues: { timer: ['timeout (5000ms) - chua het han'] },
      threadPool: ['SQL: SELECT * FROM users ...'],
      badge: { text: '11', color: '#f59e0b' },
    },
    {
      title: 'Pending Callbacks Phase',
      desc: 'Phase nay xu ly cac system-level callbacks nhu TCP errors (ECONNREFUSED). Hien tai khong co pending callback nao. Day la phase it gap nhat trong thuc te.',
      activePhase: 'pending',
      highlightLines: [],
      callStack: [],
      queues: { timer: ['timeout (5000ms)'] },
      threadPool: ['SQL: SELECT * FROM users ...'],
      badge: { text: '12', color: '#ef4444' },
    },
    {
      title: 'Idle/Prepare Phase',
      desc: 'Day la internal phase cua libuv, dung de chuan bi cho Poll phase (tinh toan poll timeout, setup watchers). Khong co JS callback nao chay o day - hoan toan la viec cua libuv internal.',
      activePhase: 'idle',
      highlightLines: [],
      callStack: [],
      queues: { timer: ['timeout (5000ms)'] },
      threadPool: ['SQL: SELECT * FROM users ...'],
      badge: { text: '13', color: '#6b7280' },
    },
    {
      title: 'Poll Phase: Cho I/O',
      desc: 'Event loop quay lai Poll phase. Khong co callback nao trong queue. Vi con timer pending (5s) va I/O (DB query), event loop se BLOCK o day cho den khi co I/O event hoac timer het han.',
      activePhase: 'poll',
      highlightLines: [],
      callStack: [],
      queues: { timer: ['timeout (5000ms)'] },
      threadPool: ['SQL: SELECT * FROM users ... (running)'],
      badge: { text: '14', color: '#3b82f6' },
    },
    {
      title: 'DB Query hoan thanh! (Thread Pool -> Poll Queue)',
      desc: 'Thread pool hoan thanh SQL query. Ket qua duoc day vao poll queue duoi dang callback. Event loop (dang block o poll) lap tuc nhan duoc event nay.',
      activePhase: 'poll',
      highlightLines: ['db-query'],
      callStack: [],
      queues: { poll: ['db.query callback (user data)'], timer: ['timeout (5000ms)'] },
      threadPool: [],
      badge: { text: '15', color: '#3b82f6' },
    },
    {
      title: 'Poll: Xu ly DB callback -> Promise resolve',
      desc: 'DB callback chay, resolve Promise cua userPromise. Viec nay day 1 microtask vao Promise queue (de resume async function). await userPromise se duoc "unblock".',
      activePhase: 'poll',
      highlightLines: ['db-query', 'db-end'],
      callStack: ['db.queryCallback()', 'promise.resolve(userData)'],
      queues: { promise: ['resume routeHandler()'], timer: ['timeout (5000ms)'] },
      threadPool: [],
      badge: { text: '16', color: '#3b82f6' },
    },
    {
      title: 'Microtasks: Check nextTick queue',
      desc: 'Sau moi macrotask callback, event loop drain microtasks. nextTick luon duoc check TRUOC Promise. Hien tai nextTick queue rong (khong co ai goi process.nextTick() trong DB callback).',
      activePhase: null,
      activeMicrotask: 'nexttick',
      highlightLines: [],
      executedLines: ['db-query', 'db-sql', 'db-param', 'db-end'],
      callStack: [],
      queues: { nexttick: [], promise: ['resume routeHandler()'], timer: ['timeout (5000ms)'] },
      threadPool: [],
      badge: { text: '17', color: '#ec4899' },
    },
    {
      title: 'Microtasks: Resume async handler',
      desc: 'nextTick rong, chuyen sang Promise queue. Tim thay "resume routeHandler()". Async function tiep tuc tu sau dong await.',
      activePhase: null,
      activeMicrotask: 'promise',
      highlightLines: ['await-db'],
      executedLines: ['db-query', 'db-sql', 'db-param', 'db-end'],
      callStack: ['routeHandler() [resumed]'],
      queues: { promise: [], timer: ['timeout (5000ms)'] },
      threadPool: [],
      badge: { text: '18', color: '#06b6d4' },
    },
    {
      title: 'Sync: Schedule setImmediate',
      desc: 'Code tiep tuc dong bo. setImmediate(fn) day callback vao Check queue. No se chay o Check phase (ngay sau Poll phase hien tai).',
      activePhase: null,
      highlightLines: ['immediate-schedule', 'immediate-body', 'immediate-end'],
      callStack: ['routeHandler()', 'setImmediate()'],
      queues: { check: ['cache update'], timer: ['timeout (5000ms)'] },
      threadPool: [],
      badge: { text: '19', color: '#10b981' },
    },
    {
      title: 'Sync: clearTimeout + Send response',
      desc: 'clearTimeout() huy bo timer 5s (vi request da thanh cong). reply.send() gui HTTP response ve client. routeHandler() hoan thanh va thoat khoi call stack.',
      activePhase: null,
      highlightLines: ['clear-timeout', 'send-response'],
      executedLines: ['timer-schedule', 'timer-body', 'timer-end'],
      callStack: ['routeHandler()', 'reply.send({ user })'],
      queues: { check: ['cache update'] },
      threadPool: [],
      badge: { text: '20', color: '#22c55e' },
    },
    {
      title: 'Check Phase: setImmediate callback',
      desc: 'Event loop chuyen sang Check phase. Tim thay "cache update" callback trong queue. Day len call stack va thuc thi.',
      activePhase: 'check',
      highlightLines: ['immediate-body'],
      executedLines: ['immediate-schedule', 'immediate-end', 'clear-timeout', 'send-response'],
      callStack: ['setImmediateCallback()', 'console.log("cache update")'],
      queues: { check: [] },
      threadPool: [],
      badge: { text: '21', color: '#10b981' },
    },
    {
      title: 'Close Callbacks Phase',
      desc: 'Phase cuoi cua vong lap. Khong co socket.on("close") nao duoc trigger trong request nay. Queue rong, event loop hoan thanh vong lap va quay ve Poll phase.',
      activePhase: 'close',
      highlightLines: [],
      executedLines: ['immediate-schedule', 'immediate-body', 'immediate-end', 'clear-timeout', 'send-response'],
      callStack: [],
      queues: {},
      threadPool: [],
      badge: { text: '22', color: '#8b5cf6' },
    },
    {
      title: 'Hoan thanh! Event loop tiep tuc',
      desc: 'Tat ca queues rong, khong con timer nao. Event loop quay ve Poll phase va BLOCK cho request tiep theo. Toan bo request chi chay tren 1 SINGLE THREAD, khong bao gio block!',
      activePhase: 'poll',
      highlightLines: [],
      callStack: [],
      queues: {},
      threadPool: [],
      badge: { text: '✓', color: '#22c55e' },
    },
  ],
}
