import type { Scenario } from './types'

export const scenario: Scenario = {
  id: 'http-request-lifecycle',
  title: 'Event Loop Architecture',
  codeLines: [
    { text: "const app = require('fastify')();", id: 'setup' },
    { text: '', id: 'blank1' },
    { text: "app.get('/api/user/:id', async (req, reply) => {", id: 'handler-start' },
    { text: "  console.log('Handler called');", id: 'handler-log' },
    { text: '', id: 'blank2' },
    { text: '  // Schedule microtasks', id: 'comment-micro' },
    { text: '  process.nextTick(() => {', id: 'nexttick-schedule' },
    { text: "    console.log('nextTick: validate session');", id: 'nexttick-body' },
    { text: '  });', id: 'nexttick-end' },
    { text: '', id: 'blank3' },
    { text: '  const userPromise = db.query(', id: 'db-query' },
    { text: "    'SELECT * FROM users WHERE id = $1',", id: 'db-sql' },
    { text: '    [req.params.id]', id: 'db-param' },
    { text: '  );', id: 'db-end' },
    { text: '', id: 'blank4' },
    { text: '  // Schedule timer for timeout', id: 'comment-timer' },
    { text: '  const timeout = setTimeout(() => {', id: 'timer-schedule' },
    { text: "    console.log('Timeout: request too slow');", id: 'timer-body' },
    { text: '  }, 5000);', id: 'timer-end' },
    { text: '', id: 'blank5' },
    { text: '  // Await DB result (I/O)', id: 'comment-io' },
    { text: '  const user = await userPromise;', id: 'await-db' },
    { text: '', id: 'blank6' },
    { text: '  // After I/O: schedule cleanup', id: 'comment-after' },
    { text: '  setImmediate(() => {', id: 'immediate-schedule' },
    { text: "    console.log('setImmediate: cache update');", id: 'immediate-body' },
    { text: '  });', id: 'immediate-end' },
    { text: '', id: 'blank7' },
    { text: '  clearTimeout(timeout);', id: 'clear-timeout' },
    { text: '  reply.send({ user });', id: 'send-response' },
    { text: '});', id: 'handler-close' },
    { text: '', id: 'blank8' },
    { text: 'app.listen({ port: 3000 });', id: 'listen' },
  ],
  steps: [
    {
      title: 'HTTP Request arrives',
      desc: 'Client sends GET /api/user/42. The OS kernel receives the request and notifies libuv via epoll/kqueue. The event loop is in Poll phase, picks up the event and creates a callback.',
      activePhase: null,
      highlightLines: ['listen'],
      callStack: [],
      queues: { poll: ['http.onRequest(GET /api/user/42)'] },
      threadPool: [],
      badge: { text: '1', color: '#22c55e' },
    },
    {
      title: 'Poll Phase: Process I/O callback',
      desc: 'Event loop is in Poll phase. It dequeues the callback and pushes it onto the Call Stack. The route handler starts executing SYNCHRONOUSLY.',
      activePhase: 'poll',
      highlightLines: ['handler-start', 'handler-log'],
      callStack: ['http.onRequest()', 'routeHandler(req, reply)'],
      queues: { poll: [] },
      threadPool: [],
      badge: { text: '2', color: '#3b82f6' },
    },
    {
      title: 'Sync: Schedule nextTick',
      desc: 'Synchronous code calls process.nextTick(). The callback does NOT run immediately — it is pushed onto the nextTick queue. This is the highest-priority microtask.',
      activePhase: 'poll',
      highlightLines: ['nexttick-schedule', 'nexttick-body', 'nexttick-end'],
      callStack: ['routeHandler()', 'process.nextTick()'],
      queues: { nexttick: ['validate session'] },
      threadPool: [],
      badge: { text: '3', color: '#ec4899' },
    },
    {
      title: 'Sync: Schedule DB query (I/O)',
      desc: 'db.query() sends the SQL query. This is delegated to the libuv Thread Pool (for disk/network I/O). The main thread is NOT blocked and continues executing synchronous code.',
      activePhase: 'poll',
      highlightLines: ['db-query', 'db-sql', 'db-param', 'db-end'],
      callStack: ['routeHandler()', 'db.query()'],
      queues: { nexttick: ['validate session'] },
      threadPool: ['SQL: SELECT * FROM users WHERE id=42'],
      badge: { text: '4', color: '#f97316' },
    },
    {
      title: 'Sync: Schedule setTimeout',
      desc: 'setTimeout(fn, 5000) registers a timer. The callback does not run yet — it will be added to the Timer queue after 5s. Timers are managed by libuv using a min-heap.',
      activePhase: 'poll',
      highlightLines: ['timer-schedule', 'timer-body', 'timer-end'],
      callStack: ['routeHandler()', 'setTimeout()'],
      queues: { nexttick: ['validate session'], timer: ['timeout (5000ms)'] },
      threadPool: ['SQL: SELECT * FROM users ...'],
      badge: { text: '5', color: '#f59e0b' },
    },
    {
      title: 'Sync: await userPromise',
      desc: 'Hits await — routeHandler() is PAUSED (exits the call stack). Control returns to the event loop. But first, all MICROTASKS must be drained.',
      activePhase: 'poll',
      highlightLines: ['await-db'],
      callStack: [],
      queues: { nexttick: ['validate session'], timer: ['timeout (5000ms)'] },
      threadPool: ['SQL: SELECT * FROM users ...'],
      badge: { text: '6', color: '#3b82f6' },
    },
    {
      title: 'Microtasks: Drain nextTick queue',
      desc: 'Before transitioning phases, the event loop DRAINS the entire nextTick queue. nextTick has higher priority than Promise. The "validate session" callback is pushed onto the call stack and executed.',
      activePhase: null,
      activeMicrotask: 'nexttick',
      highlightLines: ['nexttick-body'],
      executedLines: ['nexttick-schedule', 'nexttick-end'],
      callStack: ['nextTickCallback()', 'console.log("validate session")'],
      queues: { nexttick: [], timer: ['timeout (5000ms)'] },
      threadPool: ['SQL: SELECT * FROM users ...'],
      badge: { text: '7', color: '#ec4899' },
    },
    {
      title: 'Microtasks: Check Promise queue',
      desc: 'After nextTick is drained, the event loop checks the Promise queue. Currently empty (DB query is still running). The event loop continues its cycle.',
      activePhase: null,
      activeMicrotask: 'promise',
      highlightLines: [],
      callStack: [],
      queues: { timer: ['timeout (5000ms)'] },
      threadPool: ['SQL: SELECT * FROM users ...'],
      badge: { text: '8', color: '#06b6d4' },
    },
    {
      title: 'Check Phase: setImmediate queue',
      desc: 'Event loop moves to Check phase. No setImmediate callbacks have been scheduled yet, so this phase is skipped.',
      activePhase: 'check',
      highlightLines: [],
      callStack: [],
      queues: { timer: ['timeout (5000ms)'] },
      threadPool: ['SQL: SELECT * FROM users ...'],
      badge: { text: '9', color: '#10b981' },
    },
    {
      title: 'Close Callbacks Phase',
      desc: 'Last phase of the cycle. No socket close events to process. Skipped — a NEW LOOP ITERATION begins.',
      activePhase: 'close',
      highlightLines: [],
      callStack: [],
      queues: { timer: ['timeout (5000ms)'] },
      threadPool: ['SQL: SELECT * FROM users ...'],
      badge: { text: '10', color: '#8b5cf6' },
    },
    {
      title: 'Timers Phase (new iteration)',
      desc: 'New loop iteration starts at Timers phase. setTimeout(5000ms) has not expired yet (only a few ms in). No timers to process, event loop moves to the next phase.',
      activePhase: 'timers',
      highlightLines: [],
      callStack: [],
      queues: { timer: ['timeout (5000ms) - not expired'] },
      threadPool: ['SQL: SELECT * FROM users ...'],
      badge: { text: '11', color: '#f59e0b' },
    },
    {
      title: 'Pending Callbacks Phase',
      desc: 'This phase handles system-level callbacks like TCP errors (ECONNREFUSED). No pending callbacks at the moment. This is the least commonly triggered phase in practice.',
      activePhase: 'pending',
      highlightLines: [],
      callStack: [],
      queues: { timer: ['timeout (5000ms)'] },
      threadPool: ['SQL: SELECT * FROM users ...'],
      badge: { text: '12', color: '#ef4444' },
    },
    {
      title: 'Idle/Prepare Phase',
      desc: 'This is an internal libuv phase used to prepare for Poll phase (calculate poll timeout, set up watchers). No JS callbacks run here — entirely libuv internals.',
      activePhase: 'idle',
      highlightLines: [],
      callStack: [],
      queues: { timer: ['timeout (5000ms)'] },
      threadPool: ['SQL: SELECT * FROM users ...'],
      badge: { text: '13', color: '#6b7280' },
    },
    {
      title: 'Poll Phase: Waiting for I/O',
      desc: 'Event loop returns to Poll phase. No callbacks in the queue. Since there are pending timers (5s) and I/O (DB query), the event loop BLOCKS here until an I/O event arrives or a timer expires.',
      activePhase: 'poll',
      highlightLines: [],
      callStack: [],
      queues: { timer: ['timeout (5000ms)'] },
      threadPool: ['SQL: SELECT * FROM users ... (running)'],
      badge: { text: '14', color: '#3b82f6' },
    },
    {
      title: 'DB Query complete! (Thread Pool → Poll Queue)',
      desc: 'Thread pool finishes the SQL query. The result is pushed into the poll queue as a callback. The event loop (blocking in poll) immediately picks up this event.',
      activePhase: 'poll',
      highlightLines: ['db-query'],
      callStack: [],
      queues: { poll: ['db.query callback (user data)'], timer: ['timeout (5000ms)'] },
      threadPool: [],
      badge: { text: '15', color: '#3b82f6' },
    },
    {
      title: 'Poll: Process DB callback → Promise resolve',
      desc: 'DB callback runs and resolves the userPromise. This pushes a microtask into the Promise queue (to resume the async function). await userPromise will be "unblocked".',
      activePhase: 'poll',
      highlightLines: ['db-query', 'db-end'],
      callStack: ['db.queryCallback()', 'promise.resolve(userData)'],
      queues: { promise: ['resume routeHandler()'], timer: ['timeout (5000ms)'] },
      threadPool: [],
      badge: { text: '16', color: '#3b82f6' },
    },
    {
      title: 'Microtasks: Check nextTick queue',
      desc: 'After each macrotask callback, the event loop drains microtasks. nextTick is always checked BEFORE Promise. Currently the nextTick queue is empty (no process.nextTick() was called in the DB callback).',
      activePhase: null,
      activeMicrotask: 'nexttick',
      highlightLines: [],
      executedLines: ['db-query', 'db-sql', 'db-param', 'db-end'],
      callStack: [],
      queues: { nexttick: [], promise: ['resume routeHandler()'], timer: ['timeout (5000ms)'] },
      threadPool: [],
      badge: { text: '17', color: '#ec4899' },
    },
    {
      title: 'Microtasks: Resume async handler',
      desc: 'nextTick is empty, moves to Promise queue. Finds "resume routeHandler()". The async function continues from after the await statement.',
      activePhase: null,
      activeMicrotask: 'promise',
      highlightLines: ['await-db'],
      executedLines: ['db-query', 'db-sql', 'db-param', 'db-end'],
      callStack: ['routeHandler() [resumed]'],
      queues: { promise: [], timer: ['timeout (5000ms)'] },
      threadPool: [],
      badge: { text: '18', color: '#06b6d4' },
    },
    {
      title: 'Sync: Schedule setImmediate',
      desc: 'Code continues synchronously. setImmediate(fn) pushes the callback into the Check queue. It will run in Check phase (right after the current Poll phase).',
      activePhase: null,
      highlightLines: ['immediate-schedule', 'immediate-body', 'immediate-end'],
      callStack: ['routeHandler()', 'setImmediate()'],
      queues: { check: ['cache update'], timer: ['timeout (5000ms)'] },
      threadPool: [],
      badge: { text: '19', color: '#10b981' },
    },
    {
      title: 'Sync: clearTimeout + Send response',
      desc: 'clearTimeout() cancels the 5s timer (request succeeded in time). reply.send() sends the HTTP response back to the client. routeHandler() completes and exits the call stack.',
      activePhase: null,
      highlightLines: ['clear-timeout', 'send-response'],
      executedLines: ['timer-schedule', 'timer-body', 'timer-end'],
      callStack: ['routeHandler()', 'reply.send({ user })'],
      queues: { check: ['cache update'] },
      threadPool: [],
      badge: { text: '20', color: '#22c55e' },
    },
    {
      title: 'Check Phase: setImmediate callback',
      desc: 'Event loop moves to Check phase. Finds the "cache update" callback in the queue. Pushes it onto the call stack and executes it.',
      activePhase: 'check',
      highlightLines: ['immediate-body'],
      executedLines: ['immediate-schedule', 'immediate-end', 'clear-timeout', 'send-response'],
      callStack: ['setImmediateCallback()', 'console.log("cache update")'],
      queues: { check: [] },
      threadPool: [],
      badge: { text: '21', color: '#10b981' },
    },
    {
      title: 'Close Callbacks Phase',
      desc: 'Last phase of the loop. No socket.on("close") was triggered during this request. Queue is empty, event loop completes the iteration and returns to Poll phase.',
      activePhase: 'close',
      highlightLines: [],
      executedLines: ['immediate-schedule', 'immediate-body', 'immediate-end', 'clear-timeout', 'send-response'],
      callStack: [],
      queues: {},
      threadPool: [],
      badge: { text: '22', color: '#8b5cf6' },
    },
    {
      title: 'Complete! Event loop continues',
      desc: 'All queues are empty, no timers remaining. The event loop returns to Poll phase and BLOCKS waiting for the next request. The entire request ran on a SINGLE THREAD, never blocking!',
      activePhase: 'poll',
      highlightLines: [],
      callStack: [],
      queues: {},
      threadPool: [],
      badge: { text: '✓', color: '#22c55e' },
    },
  ],
}
